version: 2

models:
  - name: dim_product
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: dim_store
    columns:
      - name: store_id
        tests:
          - not_null
          - unique

  - name: fct_transactions
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique